version: '3.8'

services:
  airflow:
    image: vayurobotics/vayu-infrastructure
    container_name: vayu-infrastructure
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://robot_user:robot_pass@localhost:5432/robot_db
      - POSTGRES_USER=robot_user
      - POSTGRES_PASSWORD=robot_pass
      - POSTGRES_DB=robot_db
      - PYTHONPATH=/src
      - STABLE_WIFI_SSID=${STABLE_WIFI_SSID}
    volumes:
      - ./src/airflow_dags/:/usr/local/airflow/dags
      - /data:/data
      - ./pgdata:/var/lib/postgresql/data
      - ./src/:/src
    ports:
      - "8080:8080"
      - "5432:5432"
    entrypoint: /entrypoint.sh
    tty: true
    privileged: true
    network_mode: "host"
    # networks:
    #   - vayu-infrastructure_default

# networks:
#   vayu-infrastructure_default:
#     external: true
